resolver: lts-22.39

ghc-options:
  "$everything": -haddock

packages:
- tang

extra-deps:
- int-like-0.1.2
- prop-unit-0.1.3
- git: git@github.com:IagoAbal/haskell-z3
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
