resolver: lts-23.0

ghc-options:
  "$everything": -haddock

packages:
- tang

extra-deps:
- int-like-0.1.4
- prop-unit-0.1.4
- unimap-0.1.0
# TODO use hackage release when available
# Upstream: git@github.com:IagoAbal/haskell-z3
- git: https://github.com/ejconlon/haskell-z3.git
  commit: b77a17e5eeb7db82656bcbcd66c6e952207e69ca
