name: tang
version: 0.1.0

github: ejconlon/tang
license: BSD3
author: Eric Conlon
maintainer: ejconlon@gmail.com
copyright: (c) 2024 Eric Conlon
synopsis: ecta implementation
description: Please see the README on GitHub at <https://github.com/ejconlon/tang#readme>
tested-with: GHC == 9.6.6

defaults:
  local: ../defaults.yaml

dependencies:
- base >= 4.12 && < 5
- logict
- mtl
- transformers
- text
- containers
- recursion-schemes
- int-like >= 0.1.3
- z3 >= 411.0.1
- these
- optics
# test deps
- prop-unit >= 0.1.3
# dev deps
- placeholder
- pretty-show

library:
  source-dirs: src

tests:
  tang-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tang
